# Generated by Django 4.2.7 on 2025-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq_created_at_techsupportfeedback_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Уведомление')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='techsupportfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос в техническую поддержку', 'verbose_name_plural': 'Запросы в техническую поддержку'},
        ),
    ]
