# Generated by Django 4.2.7 on 2025-03-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notifications_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
