# Generated by Django 4.2.7 on 2025-03-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_notifications_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupportfeedback',
            name='phone',
            field=models.CharField(verbose_name='Номер телефона'),
        ),
    ]
