# Generated by Django 4.2.7 on 2025-03-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_populardestination_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populardestination',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='city_code',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='city_name_ru',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='interline_route',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='own_route',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='point_name_ru',
        ),
        migrations.RemoveField(
            model_name='populardestination',
            name='popular',
        ),
    ]
