# Generated by Django 4.2.7 on 2025-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitrix UserId'),
        ),
    ]
